#!/bin/sh

displayLayout=$(setxkbmap -query | awk '/layout:/ {print $2}')

case $BLOCK_BUTTON in
        1) notify-send "<b>Layout Indicator</b>:
Module for displaying current keyboard layout
- press 'mod + space' to switch layout ";;
#        3) notify-send "<b>bold text</b>
#- item1
#- item2
#- item3" ;;
esac

echo $displayLayout
