#!/bin/bash

layout=$(setxkbmap -query | awk '/layout:/ {print $2}')

if [ $layout = "cz" ]; then
	setxkbmap us
fi

rm -f /tmp/locked.png

scrot -m -z /tmp/base.png
convert /tmp/base.png -blur 0x8 /tmp/locked.png
i3lock -e -f -i /tmp/locked.png
pgrep -x i3lock && xset dpms force off
