#!/bin/bash

#revert() {
#  rm /tmp/*screen*.png
#  xset dpms 0 0 0
#}
#trap revert HUP INT TERM
#xset +dpms dpms 0 0 5
#scrot -m -z /tmp/locking_screen.png
#notify-send -i ~/.scripts/lock.png "Locking computer..." 
#convert -blur 0x8 /tmp/locking_screen.png /tmp/screen_blur.png
#sleep 2s
#i3lock -i /tmp/screen_blur.png
#revert

revert() {
  rm /tmp/*screen*.png
  xset dpms 0 0 0
}
trap revert HUP INT TERM
xset +dpms dpms 0 0 5
scrot -m -z /tmp/locking_screen.png
convert -blur 0x8 /tmp/locking_screen.png /tmp/screen_blur.png
i3lock -i /tmp/screen_blur.png
revert
